version: '3.8'

services:
  streamlit-app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MAX_FILE_SIZE=10GB
    volumes:
      - ./temp:/app/temp
      - ./output:/app/output
    restart: unless-stopped